version: "3.8"

services:
  backend_test:
    container_name: backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    tty: true
    volumes:
      - ./backend:/backend

volumes:
  pgdata:

